# Generated by Django 5.1.5 on 2025-01-20 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id_island', models.AutoField(primary_key=True, serialize=False)),
                ('dream_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('aesth_rating', models.IntegerField()),
                ('motif_rating', models.IntegerField()),
                ('creat_rating', models.IntegerField()),
                ('rating', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('id_island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.island')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
