# Generated by Django 5.1.5 on 2025-01-22 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='started',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
