# Generated by Django 5.1.5 on 2025-01-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_review_comment_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='dream_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
